#!/bin/bash

# This is a bash script to install LunarG VulkanSDK in Ubuntu 16.04.
# Author     : sunbearc22
# Created on : 2017-10-5
# Modified on: 2018-07-24
# Remarks    : Vulkan Installation Analyzer (VIA) returned Successful.    
#               1.1.77.0   1.1.73.0   1.1.70.1*   1.1.70.0
#
#               1.0.68.0   1.0.65.0   1.0.61.0   1.0.57.0   1.0.54.0   1.0.51.0   1.0.49.0   
#               1.0.46.0   1.0.42.2   1.0.39.1   1.0.39.0
#
#  * symbol denotes encountered compiling error.
	
echo
echo "============================================================"
echo "Program to locally install VulkanSDK in "$USER"'s directory."
echo "============================================================"
echo "Enter the version (e.g. 1.0.61.1) to be installed and press [ENTER]:"
read version
echo "Specify the Vulkan directory and path (e.g. ~/Vulkan) and press [ENTER]:"
read vpath
vpath="${vpath/#\~/$HOME}" #convert ~ to $HOME if ~ exist

if [ $version = "1.1.77.0" ]; then
    echo "1.1.77.0"
    filename="vulkansdk-linux-$version.tar.gz"
else
    filename="vulkansdk-linux-$version.run"
fi
url="https://sdk.lunarg.com/sdk/download/$version/linux/$filename?Human=true"

oldPATH=$PATH  #backup PATH variable

echo "version  = " $version
echo "vpath    = " $vpath
echo "filename = " $filename
echo "url      = " $url
echo "oldPATH  = " $oldPATH

echo
echo "Step 1. Update and Upgrade System Packages."
sudo apt-get update
sudo apt-get dist-upgrade

echo
echo "Step2. Install Prerequisite Packages."
sudo apt-get install libglm-dev cmake libxcb-dri3-0 libxcb-present0 libpciaccess0 \
libpng-dev libxcb-keysyms1-dev libxcb-dri3-dev libxrandr-dev \
libx11-dev libxcb1-dev libxkbcommon-dev libmirclient-dev libwayland-dev \
graphviz git libpython2.7

echo
echo "Step 3. Download Vulkan SDK Installer to $vpath."
if [ ! -f $vpath/$filename ]; then
    wget $url -O $vpath/$filename
else
    echo "$vpath/$filename exist. Download of VulkanSDK is not required."
fi

echo
echo "Step 4. Install LunarG VulkanSDK."
if [ $version = "1.1.77.0" ]; then
    echo "1.1.77.0"
    mkdir -p $vpath/VulkanSDK
    tar xf $vpath/$filename -C $vpath/VulkanSDK
    cd  $vpath/VulkanSDK/$version
    
else
    echo "Not 1.1.77.0"
    chmod ugo+x $vpath/$filename  #Make SDK file executable 
    cd $vpath
    ./$filename
    cd VulkanSDK/$version
fi

echo
echo "Step 5. Setup Vulkan Runtime Environment."
source $vpath/VulkanSDK/$version/setup-env.sh  #export Vulkan environment variables
export PATH="$VULKAN_SDK/bin:$oldPATH"

echo
echo "Step 6. Simple Verification of Vulkan SDK Installation."
./x86_64/bin/vulkaninfo

echo
echo "Step 7. Build Vulkan examples."
./build_examples.sh

echo
echo "Step 8. Build Vulkan samples."
./build_samples.sh

echo
echo "Step 9. Build Vulkan tools."
./build_tools.sh

echo
echo "Step 10. Run Vulkan Installation Analyzer."
./x86_64/bin/via

echo
echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
echo "                   End of installVulkanSDK."
echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
echo 
echo " Please manually vet through the build statements for warnings"
echo " and errors. Their absence verifies that:"
echo "  - Vulkan SDK $version and its tools, examples and samples"
echo "    have been built and installed succesfully."
echo 
echo "             Enjoy the power of VULKAN $version."
echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"

unset version vpath filename url #remove local environment variables
#Note env variable oldPATH is not deleted.
